application: ucl2icsphp
version: 6
runtime: php
api_version: 1

handlers:
- url: /(.*\.(css|ico|html|js))
  static_files: \1
  upload: (.*\.(css|ico|html|js))
  
- url: /admin
  script: admin.php
  
- url: /.*
  script: ade.php
